### ISSUE TITLE
Can't seem to build project

### ISSUE THREAD

**Issue by ibussieres** [soutot/react-native-orientation-test#1]
Hey, I'm willing to help out a bit, but I can't seem to build your project and don't have much time to start debugging why. Can you get it to build on latest version of RN and if your orientation still does not work, I'll look into helping out on that aspect.

![image](https://cloud.githubusercontent.com/assets/422296/24512041/780b00a2-153b-11e7-807b-e975dcfa5e7e.png)

**Comment by soutot** [comment]
Hi! Thanks, you made me check an error that I wasn't aware of.
After fixing the build you mentioned, I found that there was an error of ```RCTBridgeModule.h' file not found```
I replaced it the import to this ```#import <React/RCTBridgeModule.h>``` and it seems to be working now!

Thank you very much!

**Comment by soutot** [comment]
![Demo](https://media.giphy.com/media/3og0IUNzhuZNalibLO/giphy.gif)
